project:
  type: website

website:
  title: "Victor Lao's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - menu:
        - href: https://app.powerbi.com/view?r=eyJrIjoiYTZiZjJkMGEtNDZlNy00YWRkLTgyYTAtYzI2OTMwMjllZDQxIiwidCI6IjY0MmE2ZGUyLTJiODktNDJkOC05MDZhLTIxM2E4NWEzZTMxOCJ9
          text: Canadian Provincial Rent Power BI Dashboard
        - href: https://szys2b-victor-lao.shinyapps.io/video_game_analysis_2024
          text: Metacritic Featured Games Shiny App
        - href: https://github.com/Spingelhoff/fileR
          text: fileR Package
        text: Projects
      - href: listings.qmd
        text: Reports
      - href: Resume.pdf
        text: Resume

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

