project:
  type: website
  output-dir: docs
website:
  google-analytics: "G-S4NG67LZ08"
  title: "Victor Lao's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: listings.qmd
        text: Reports
      - href: Resume.pdf
        text: Resume

format:
  html:
    theme: lux
    css: styles.css
    toc: false

editor: visual

