---
title: "Network Mapping the Most Influential Addresses using DAI (2021): Extracting Blockchain Data from Public Google Datasets with BigQuery and SQL"
author: "Victor Lao"
date: 2022-08-30
output: 
  blogdown::html_page:
    toc: TRUE
---

## Introduction

Blockchain technologies are inarguably reshaping how the general public thinks
of finance. One particularly interesting innovation is the concept of
decentralized autonomous organizations (or DAOs). Leveraging the transparency of
the blockchain, DAOs endeavour to collaboratively run organizations in a 
trustless way. This novel method of conducting corporate operations makes a 
compelling subject for analysis.

One prominent DAO is MakerDAO. They are most well known for their 
over-collateralized USD stable coin, DAI. As all core MakerDAO operations and
products operate through the blockchain, I retrieved all emitted event logs 
pertaining to MakerDAO smart contracts (executes blockchain functions) using
BigQuery and the MakerDAO technical docs.

## Methodology

Table of MakerDAO events was created using the publicly available Ethereum
blockchain dataset on BigQuery. As addresses are stored on the blockchain as
a 42 character hexadecimal, all smart contract addresses were converted to their
contract name using MakerDAO technical docs. Topic 0 of event logs typically
contains a unqiue event type specific index and was used to annotate function 
events. Each unique event type was individually parsed for sender identity,
reciever identity and value. Makerdao stores values as integers which stand for
differing decimals of percision depending on the event type. An unfortunate
side effect of this storage method is that the values are too large for BigQuery
to handle (can only go up to INT64). This necessitated using R to view the
correct values. Values were stored on BigQuery as hexadecimals.
```{sql eval=FALSE}
CREATE TABLE 
     makerdao_operations.may2021to2022
PARTITION BY DATE (
     block_timestamp
)
CLUSTER BY
     makerdao_smartcontract,
     makerdao_function
AS (

SELECT
     logs.block_timestamp AS block_timestamp,
     transaction_hash,
     from_address,
     to_address,
     value AS eth_value,
     gas_price,
     CASE
          WHEN address = '0x6b175474e89094c44da98b954eedeac495271d0f' THEN 'DAI'
          WHEN address = '0x9759A6Ac90977b93B58547b4A71c78317f391A28' THEN 'DAIJOIN'
          WHEN address = '0x2F0b23f53734252Bda2277357e97e1517d6B042A' THEN 'GEMJOIN'
          WHEN address = '0x197E90f9FAD81970bA7976f33CbD77088E5D7cf7' THEN 'POT'
          WHEN address = '0x19c0976f590D67707E62397C87829d896Dc0f1F1' THEN 'JUG'
          WHEN address = '0xA950524441892A31ebddF91d3cEEFa04Bf454466' THEN 'VOW'
          WHEN address = '0xC4269cC7acDEdC3794b221aA4D9205F564e27f0d' THEN 'FLAPPER'
          WHEN address = '0xA41B6EF151E06da0e34B009B86E828308986736D' THEN 'FLOPPER'
          WHEN address = '0x35D1b3F3D7966A1DFe207aa4514C12a259A0492B' THEN 'VAT'
          WHEN address = '0x65C79fcB50Ca1594B025960e539eD7A9a6D434A3' THEN 'SPOT'
          WHEN address = '0x135954d155898D42C90D2a57824C690e0c7BEf1B' THEN 'DOG'
          WHEN address = '0xc67963a226eddd77B91aD8c421630A1b0AdFF270' THEN 'CLIPPER'
          WHEN address = '0x1EB4CF3A948E7D72A198fe073cCb8C7a948cD853' THEN 'FLASH'
          WHEN address = '0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2' THEN 'MKR'
          WHEN address = '0x0a3f6849f78076aefaDf113F5BED87720274dDC0' THEN 'DSCHIEF'
          WHEN address = '0xA618E54de493ec29432EbD2CA7f14eFbF6Ac17F7' THEN 'DSTOKEN'
          WHEN address = '0x82ecD135Dce65Fbc6DbdD0e4237E0AF93FFD5038' THEN 'PROXY'
          WHEN address = '0x5ef30b9986345249bc32d8928B7ee64DE9435E39' THEN 'CDPMANAGER'
               END AS makerdao_smartcontract,
     CASE
          WHEN topics[OFFSET(0)] = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef' AND
               topics[OFFSET(1)] NOT IN (
                                        '0x0000000000000000000000000000000000000000',
                                        '0x2F0b23f53734252Bda2277357e97e1517d6B042A',
                                        '0x0a3f6849f78076aefadf113f5bed87720274ddc0'
                                        )                                                               AND
               topics[OFFSET(2)] NOT IN ('0x0000000000000000000000000000000000000000',
                                        '0x2F0b23f53734252Bda2277357e97e1517d6B042A',
                                        '0x0a3f6849f78076aefadf113f5bed87720274ddc0'
                                        )                                                               THEN 'transfer' --DAI/MKR/IOU
          WHEN topics[OFFSET(0)] = '0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925' THEN 'approve' --DAI/MKR/IOU
          WHEN topics[OFFSET(0)] = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef' AND
               topics[OFFSET(1)] = '0x0000000000000000000000000000000000000000'                         THEN 'mint/exit' --DAIJOIN
          WHEN topics[OFFSET(0)] = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef' AND
               topics[OFFSET(2)] = '0x0000000000000000000000000000000000000000'                         THEN 'burn/join' --DAIJOIN
          WHEN topics[OFFSET(0)] = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef' AND
               topics[OFFSET(1)] = '0x2F0b23f53734252Bda2277357e97e1517d6B042A'                         THEN 'mint/exit' --GEMJOIN
          WHEN topics[OFFSET(0)] = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef' AND
               topics[OFFSET(2)] = '0x2F0b23f53734252Bda2277357e97e1517d6B042A'                         THEN 'burn/join' --GEMJOIN
          WHEN topics[OFFSET(0)] = '0x9f678cca00000000000000000000000000000000000000000000000000000000' THEN 'drip' --POT
          WHEN topics[OFFSET(0)] = '0x7f8661a100000000000000000000000000000000000000000000000000000000' THEN 'exit' --POT
          WHEN topics[OFFSET(0)] = '0x049878f300000000000000000000000000000000000000000000000000000000' THEN 'join' --POT
          WHEN topics[OFFSET(0)] = '0x44e2a5a800000000000000000000000000000000000000000000000000000000' THEN 'drip' --JUG
          WHEN topics[OFFSET(0)] = '0xf37ac61c00000000000000000000000000000000000000000000000000000000' THEN 'heal' --VOW/VAT
          WHEN topics[OFFSET(0)] = '0xd7ee674b00000000000000000000000000000000000000000000000000000000' THEN 'flog' --VOW
          WHEN topics[OFFSET(0)] = '0xc959c42b00000000000000000000000000000000000000000000000000000000' THEN 'deal' --FLAPPER
          WHEN topics[OFFSET(0)] = '0xa3b22fc400000000000000000000000000000000000000000000000000000000' THEN 'hope' --VAT
          WHEN topics[OFFSET(0)] = '0xdc4d20fa00000000000000000000000000000000000000000000000000000000' THEN 'nope' --VAT
          WHEN topics[OFFSET(0)] = '0xbb35783b00000000000000000000000000000000000000000000000000000000' THEN 'move' --VAT
          WHEN topics[OFFSET(0)] = '0x7cdd3fde00000000000000000000000000000000000000000000000000000000' THEN 'slip' --VAT
          WHEN topics[OFFSET(0)] = '0x7bab3f4000000000000000000000000000000000000000000000000000000000' THEN 'grab' --VAT
          WHEN topics[OFFSET(0)] = '0xdfd7467e425a8107cfd368d159957692c25085aacbcf5228ce08f10f2146486e' THEN 'poke' --SPOT
          WHEN topics[OFFSET(0)] = '0x85258d09e1e4ef299ff3fc11e74af99563f022d21f3f940db982229dc2a3358c' THEN 'bark' --DOG
          WHEN topics[OFFSET(0)] = '0x54f095dc7308776bf01e8580e4dd40fd959ea4bf50b069975768320ef8d77d8a' THEN 'digs' --DOG
          WHEN topics[OFFSET(0)] = '0x7c5bfdc0a5e8192f6cd4972f382cec69116862fb62e6abff8003874c58e064b8' THEN 'kick' --CLIPPER
          WHEN topics[OFFSET(0)] = '0x05e309fd6ce72f2ab888a20056bb4210df08daed86f21f95053deb19964d86b1' THEN 'take' --CLIPPER
          WHEN topics[OFFSET(0)] = '0x0d7d75e01ab95780d3cd1c8ec0dd6c2ce19e3a20427eec8bf53283b6fb8e95f0' THEN 'flashloan' --FLASH
          WHEN topics[OFFSET(0)] = '0xcc16f5dbb4873280815c1ee09dbd06736cffcc184412cf7a71a0fdb75d397ca5' THEN 'burn' --MKR/DSTOKEN
          WHEN topics[OFFSET(0)] = '0x0f6798a560793a54c3bcfe86a93cde1e73087d944c0ea20544137d4121396885' THEN 'mint' --MKR/DSTOKEN
          WHEN topics[OFFSET(0)] = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef' AND
               topics[OFFSET(1)] = '0x0a3f6849f78076aefadf113f5bed87720274ddc0'                         THEN 'free' --DSCHIEF
          WHEN topics[OFFSET(0)] = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef' AND
               topics[OFFSET(2)] = '0x0a3f6849f78076aefadf113f5bed87720274ddc0'                         THEN 'lock' --DSCHIEF
          WHEN topics[OFFSET(0)] = '0x4f0892983790f53eea39a7a496f6cb40e8811b313871337b6a761efc6c67bb1f' THEN 'etch' --DSCHIEF(slate) 
          WHEN topics[OFFSET(0)] IN (
                                   '0xa69beaba00000000000000000000000000000000000000000000000000000000',
                                   '0xed08132900000000000000000000000000000000000000000000000000000000'
                                   )                                                                    THEN 'vote' --DSCHIEF
          WHEN topics[OFFSET(0)] = '0xd6be0bc178658a382ff4f91c8c68b542aa6b71685b8fe427966b87745c3ea7a2' THEN 'open' --CDPMANAGER
          WHEN topics[OFFSET(0)] = '0xfcafcc6800000000000000000000000000000000000000000000000000000000' THEN 'give' --CDPMANAGER
          WHEN topics[OFFSET(0)] = '0x45e6bdcd00000000000000000000000000000000000000000000000000000000' THEN 'frob' --CDPMANAGER
          WHEN topics[OFFSET(0)] = '0x9bb8f83800000000000000000000000000000000000000000000000000000000' THEN 'flux' --CDPMANAGER
          WHEN topics[OFFSET(0)] = '0xf9f30db600000000000000000000000000000000000000000000000000000000' THEN 'move' --CDPMANAGER
          WHEN topics[OFFSET(0)] = '0x1b0dbf7200000000000000000000000000000000000000000000000000000000' THEN 'quit' --CDPMANAGER
               END AS makerdao_function,
     CASE --note following are in hex string format (as the numbers are too big for... bigquery)
          WHEN topics[OFFSET(0)] = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef' --transfer/burn/mint value
               THEN data --wad (10e18)
          WHEN topics[OFFSET(0)] = '0x7f8661a100000000000000000000000000000000000000000000000000000000' --pot/DSR exit value
               THEN topics[OFFSET(2)] --wad
          WHEN topics[OFFSET(0)] = '0x049878f300000000000000000000000000000000000000000000000000000000' --pot/DSR join value
               THEN topics[OFFSET(3)] --wad
          WHEN topics[OFFSET(0)] = '0xbb35783b00000000000000000000000000000000000000000000000000000000' --vat move value
               THEN topics[OFFSET(2)] --rad (10e45)
          WHEN topics[OFFSET(0)] = '0xf37ac61c00000000000000000000000000000000000000000000000000000000' --vow/vat heal amount
               THEN topics[OFFSET(1)] --rad
          WHEN topics[OFFSET(0)] = '0x7cdd3fde00000000000000000000000000000000000000000000000000000000' --vat slip amount
               THEN topics[OFFSET(3)] --wad
          WHEN topics[OFFSET(0)] = '0x7bab3f4000000000000000000000000000000000000000000000000000000000' --vat grab debt (dart) amount
               THEN CONCAT('0x', SUBSTR(data, 459, 64)) --wad
          WHEN topics[OFFSET(0)] = '0x85258d09e1e4ef299ff3fc11e74af99563f022d21f3f940db982229dc2a3358c' --dog bark liquidation (art)
               THEN CONCAT('0x', SUBSTR(data, 67, 64)) --wad
          WHEN topics[OFFSET(0)] = '0x7c5bfdc0a5e8192f6cd4972f382cec69116862fb62e6abff8003874c58e064b8' --clipper kick DAI debt (tab) 
               THEN CONCAT('0x', SUBSTR(data, 67, 64)) --rad
          WHEN topics[OFFSET(0)] = '0x05e309fd6ce72f2ab888a20056bb4210df08daed86f21f95053deb19964d86b1' --clipper take bid (price) 
               THEN CONCAT('0x', SUBSTR(data, 67, 64)) --ray (10e27)
          WHEN topics[OFFSET(0)] = '0x0d7d75e01ab95780d3cd1c8ec0dd6c2ce19e3a20427eec8bf53283b6fb8e95f0' --flashloan loan value (amount)
               THEN CONCAT('0x', SUBSTR(data, 67, 64)) --ray
          WHEN topics[OFFSET(0)] = '0xcc16f5dbb4873280815c1ee09dbd06736cffcc184412cf7a71a0fdb75d397ca5' --MKR/DSTOKEN burn value
               THEN data --wad
          WHEN topics[OFFSET(0)] = '0x0f6798a560793a54c3bcfe86a93cde1e73087d944c0ea20544137d4121396885' --MKR/DSTOKEN mint value
               THEN data --wad
          WHEN topics[OFFSET(0)] = '0x45e6bdcd00000000000000000000000000000000000000000000000000000000' --CDPMANAGER frob debt change
               THEN CONCAT('0x', SUBSTR(data, 267, 64)) --wad (assuming dart value of similar percision across contracts)
          WHEN topics[OFFSET(0)] = '0x9bb8f83800000000000000000000000000000000000000000000000000000000' --CDPMANAGER flux collateral
               THEN CONCAT('0x', SUBSTR(data, 203, 64)) --wad
          WHEN topics[OFFSET(0)] = '0xf9f30db600000000000000000000000000000000000000000000000000000000' --CDPMANAGER move value
               THEN CONCAT('0x', SUBSTR(data, 267, 64)) --rad
                    END AS value,
     CASE
          WHEN topics[OFFSET(0)] = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef' --transfer/burn/mint
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925' --approve
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x9f678cca00000000000000000000000000000000000000000000000000000000' --drip
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x7f8661a100000000000000000000000000000000000000000000000000000000' --exit
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x049878f300000000000000000000000000000000000000000000000000000000' --join
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x44e2a5a800000000000000000000000000000000000000000000000000000000' --drip
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0xf37ac61c00000000000000000000000000000000000000000000000000000000' --heal
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0xd7ee674b00000000000000000000000000000000000000000000000000000000' --flog
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0xc959c42b00000000000000000000000000000000000000000000000000000000' --deal
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0xa3b22fc400000000000000000000000000000000000000000000000000000000' --hope
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0xdc4d20fa00000000000000000000000000000000000000000000000000000000' --nope
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0xbb35783b00000000000000000000000000000000000000000000000000000000' --move(vat)
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x7bab3f4000000000000000000000000000000000000000000000000000000000' --grab (u; user liquidated)
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(2)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x85258d09e1e4ef299ff3fc11e74af99563f022d21f3f940db982229dc2a3358c' --bark (urn liquidated)
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(2)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x7c5bfdc0a5e8192f6cd4972f382cec69116862fb62e6abff8003874c58e064b8' --kick (auction id)
               THEN SAFE_CAST(SAFE_CAST(topics[OFFSET(1)] AS INT64) AS STRING)
          WHEN topics[OFFSET(0)] = '0x05e309fd6ce72f2ab888a20056bb4210df08daed86f21f95053deb19964d86b1' --take (who; auction bidder)
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(2)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x0d7d75e01ab95780d3cd1c8ec0dd6c2ce19e3a20427eec8bf53283b6fb8e95f0' --flashloan (reciever)
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0xcc16f5dbb4873280815c1ee09dbd06736cffcc184412cf7a71a0fdb75d397ca5' --burn (DSTOKEN)
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0xa69beaba00000000000000000000000000000000000000000000000000000000' --vote
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0xd6be0bc178658a382ff4f91c8c68b542aa6b71685b8fe427966b87745c3ea7a2' --open
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0xfcafcc6800000000000000000000000000000000000000000000000000000000' --give (cdp id)
               THEN topics[OFFSET(2)]
          WHEN topics[OFFSET(0)] = '0x45e6bdcd00000000000000000000000000000000000000000000000000000000' --frob
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x9bb8f83800000000000000000000000000000000000000000000000000000000' --flux (cpd id)
               THEN topics[OFFSET(2)]
          WHEN topics[OFFSET(0)] = '0xf9f30db600000000000000000000000000000000000000000000000000000000' --move (cdp id)
               THEN topics[OFFSET(2)]
          WHEN topics[OFFSET(0)] = '0x1b0dbf7200000000000000000000000000000000000000000000000000000000' --quit (cdp id)
               THEN topics[OFFSET(2)]
                    END AS sender,
     CASE
          WHEN topics[OFFSET(0)] = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef' --transfer/burn/mint
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(2)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925' --approve
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(2)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0xbb35783b00000000000000000000000000000000000000000000000000000000' --move(vat)
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(2)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x7cdd3fde00000000000000000000000000000000000000000000000000000000' --slip(vat)
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(2)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x7bab3f4000000000000000000000000000000000000000000000000000000000' --grab (w; user recieving debt)
               THEN CONCAT('0x', SUBSTR(data, 355, 40)) --retrieve address from data (not logged)
          WHEN topics[OFFSET(0)] = '0x85258d09e1e4ef299ff3fc11e74af99563f022d21f3f940db982229dc2a3358c' --bark (auction id)
               THEN SAFE_CAST(SAFE_CAST(topics[OFFSET(3)] AS INT64) AS STRING)
          WHEN topics[OFFSET(0)] = '0x7c5bfdc0a5e8192f6cd4972f382cec69116862fb62e6abff8003874c58e064b8' --kick (kpr of dai incentive)
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(3)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x05e309fd6ce72f2ab888a20056bb4210df08daed86f21f95053deb19964d86b1' --take (auction id)
               THEN SAFE_CAST(SAFE_CAST(topics[OFFSET(1)] AS INT64) AS STRING)
          WHEN topics[OFFSET(0)] = '0x0d7d75e01ab95780d3cd1c8ec0dd6c2ce19e3a20427eec8bf53283b6fb8e95f0' --flashloan (token)
               THEN CONCAT('0x', SUBSTR(data, 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x0f6798a560793a54c3bcfe86a93cde1e73087d944c0ea20544137d4121396885' --mint (DSTOKEN)
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x4f0892983790f53eea39a7a496f6cb40e8811b313871337b6a761efc6c67bb1f' --etch
               THEN topics[OFFSET(1)]
          WHEN topics[OFFSET(0)] = '0xa69beaba00000000000000000000000000000000000000000000000000000000' --vote (slate)
               THEN topics[OFFSET(2)]
          WHEN topics[OFFSET(0)] = '0xd6be0bc178658a382ff4f91c8c68b542aa6b71685b8fe427966b87745c3ea7a2' --open (cdp id)
               THEN topics[OFFSET(3)]
          WHEN topics[OFFSET(0)] = '0xfcafcc6800000000000000000000000000000000000000000000000000000000' --give (dst address)
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(1)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x45e6bdcd00000000000000000000000000000000000000000000000000000000' --frob (affected cdp)
               THEN topics[OFFSET(2)]
          WHEN topics[OFFSET(0)] = '0x9bb8f83800000000000000000000000000000000000000000000000000000000' --flux (dst)
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(3)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0xf9f30db600000000000000000000000000000000000000000000000000000000' --move (dst)
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(3)], 27, 40)) --remove zero padding
          WHEN topics[OFFSET(0)] = '0x1b0dbf7200000000000000000000000000000000000000000000000000000000' --quit (dst)
               THEN CONCAT('0x', SUBSTR(topics[OFFSET(3)], 27, 40)) --remove zero padding
                    END AS reciever,
     CASE WHEN topics[OFFSET(0)] IN ('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
                                     '0x7f8661a100000000000000000000000000000000000000000000000000000000',
                                     '0x049878f300000000000000000000000000000000000000000000000000000000',
                                     '0x7cdd3fde00000000000000000000000000000000000000000000000000000000',
                                     '0x7bab3f4000000000000000000000000000000000000000000000000000000000',
                                     '0x85258d09e1e4ef299ff3fc11e74af99563f022d21f3f940db982229dc2a3358c',
                                     '0xcc16f5dbb4873280815c1ee09dbd06736cffcc184412cf7a71a0fdb75d397ca5',
                                     '0x0f6798a560793a54c3bcfe86a93cde1e73087d944c0ea20544137d4121396885',
                                     '0x45e6bdcd00000000000000000000000000000000000000000000000000000000',
                                     '0x9bb8f83800000000000000000000000000000000000000000000000000000000'
                                   )
               THEN 'wad'
          WHEN topics[OFFSET(0)] IN ('0x05e309fd6ce72f2ab888a20056bb4210df08daed86f21f95053deb19964d86b1',
                                     '0x0d7d75e01ab95780d3cd1c8ec0dd6c2ce19e3a20427eec8bf53283b6fb8e95f0'
                                   )
               THEN 'ray'
          WHEN topics[OFFSET(0)] IN ('0xbb35783b00000000000000000000000000000000000000000000000000000000',
                                     '0xf37ac61c00000000000000000000000000000000000000000000000000000000',
                                     '0x7c5bfdc0a5e8192f6cd4972f382cec69116862fb62e6abff8003874c58e064b8',
                                     '0xf9f30db600000000000000000000000000000000000000000000000000000000'
                                   )
               THEN 'rad'
                    END AS percision, --see value section
     topics,
     data
FROM bigquery-public-data.crypto_ethereum.logs AS logs
RIGHT JOIN bigquery-public-data.crypto_ethereum.transactions AS transactions
     ON logs.transaction_hash = transactions.hash
WHERE logs.block_timestamp BETWEEN '2021-05-30' and '2022-05-30'
     AND address IN (
     '0x6b175474e89094c44da98b954eedeac495271d0f', -- DAI address (ERC20 form)
     '0x9759A6Ac90977b93B58547b4A71c78317f391A28', -- DAIJOIN address (mint/burn)
     '0x2F0b23f53734252Bda2277357e97e1517d6B042A', -- GEMJOIN address (collateral)
     '0x197E90f9FAD81970bA7976f33CbD77088E5D7cf7', -- POT address (savings contract)
     '0x19c0976f590D67707E62397C87829d896Dc0f1F1', -- JUG address (stability fees)
     '0xA950524441892A31ebddF91d3cEEFa04Bf454466', -- VOW address (balance sheet)
     '0xC4269cC7acDEdC3794b221aA4D9205F564e27f0d', -- FLAPPER address (surplus)
     '0xA41B6EF151E06da0e34B009B86E828308986736D', -- FLOPPER address (deficit - never been called thus far)
     '0x35D1b3F3D7966A1DFe207aa4514C12a259A0492B', -- VAT address (vaults)
     '0x135954d155898D42C90D2a57824C690e0c7BEf1B', -- DOG address (liquidations)
     '0xc67963a226eddd77B91aD8c421630A1b0AdFF270', -- CLIPPER address (liquidations)
     '0x1EB4CF3A948E7D72A198fe073cCb8C7a948cD853', -- FLASH address (flash loans)
     '0x9f8F72aA9304c8B593d555F12eF6589cC3A579A2', -- MKR address (governance ERC20)
     '0x0a3f6849f78076aefaDf113F5BED87720274dDC0', -- DSCHIEF address (governance voting system)
     '0xA618E54de493ec29432EbD2CA7f14eFbF6Ac17F7', -- DSTOKEN address (governance IOU)
     '0x82ecD135Dce65Fbc6DbdD0e4237E0AF93FFD5038', -- PROXY address (for proxy actions)
     '0x5ef30b9986345249bc32d8928B7ee64DE9435E39'  -- CDPMANAGER address (for managing vaults)
     )

)

```


## References

MakerDAO (2021). MakerDAO Technical Docs. URL https://docs.makerdao.com/

Google (2021). BigQuery. URL https://cloud.google.com/bigquery

